var pilihIdExamination;
var checked;
var role;
var id_user;
var username;
var name;
var doctor_name;
var doctor_username;
var id_penerima;
var id_doctor;
var id_pasien;
var tanggallihatgrafik;
var jamlihatgrafik;
var id_data_diagnosa;
String foto_profil;
DateTime tanggal_lahir;
String phone;
String alamat;
String eemail;
//String link = "http://34.126.80.36/dermits/";
//String link = "http://192.168.1.68/haloecg/";
String link = "http://www.komputer-its.com/haloecg/";
